name: Build BeeconMini SEED AC2 Firmware

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
    
permissions:
  contents: write
  actions: read

env:
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/BeeconMini/immortalwrt.git
  REPO_BRANCH: 24.10.1
  CONFIG_FILE: configs/seed-ac2.config
  COMMON_FILE: configs/mt7981-common.inc
  FIRMWARE_NAME: BeeconMini-SEED-AC2-immortalwrt-24.10.1
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout build scripts
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential ccache clang cmake cpio curl file flex gawk gettext git \
            gperf libncurses5-dev libssl-dev python3 rsync unzip wget \
            zlib1g-dev zstd lib32gcc-s1 libc6-dev-i386 subversion patch

      - name: Clone source
        run: |
          git clone --depth=1 -b $REPO_BRANCH $REPO_URL openwrt

      - name: Merge configs
        run: |
          cat $COMMON_FILE >> $CONFIG_FILE
          cp $CONFIG_FILE openwrt/.config
          cd openwrt
          make defconfig

      - name: Download feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile firmware
        id: compile
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Prepare artifact
        run: |
          cd openwrt/bin/targets/mediatek/mt7981/
          DATE=$(date +"%Y%m%d-%H%M")
          mkdir -p output
          for f in *squashfs-sysupgrade.bin; do
              NEW_NAME="${FIRMWARE_NAME}-${DATE}.bin"
              cp "$f" output/"$NEW_NAME"
              sha256sum output/"$NEW_NAME" > output/"$NEW_NAME".sha256
          done
          echo "date=$DATE" >> $GITHUB_ENV

      - name: Upload firmware to release
        if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: seed-ac2-${{ env.date }}
          name: "SEED AC2 Auto Build ${{ env.date }}"
          files: openwrt/bin/targets/mediatek/mt7981/output/*
          body: |
            自动生成固件（BeeconMini SEED AC2）
            - ImmortalWrt 24.10.1
            - 默认：NAT 加速 / AdGuardHome / Samba / UPnP / IPv6 / USB 存储
            - 首次刷机后请手动开启硬件加速（可选）：
              ```
              uci set firewall.@defaults[0].flow_offloading_hw='1'
              uci commit firewall
              reload_config
              ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
